# Generated by Django 3.2.13 on 2022-06-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
