# Generated by Django 3.2.13 on 2022-06-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_projects_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('start_finish', models.CharField(blank=True, max_length=255, null=True)),
                ('academy', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Skill name')),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='academy',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='content',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='start_finish',
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.resume'),
        ),
    ]
